name: Build Windows Executable

on:
  push:
    branches: [ main ] 
  workflow_dispatch: 

jobs:
  build:
    runs-on: windows-latest 

    steps:
    - name: Checkout code into a specific directory
      uses: actions/checkout@v4
      with:
        path: 'my_project_code' # Clonamos en una carpeta simple llamada 'my_project_code'

    - name: Debug Directory Structure
      shell: bash
      run: |
        echo "Initial PWD: $(pwd)"
        echo "------------------------------------"
        echo "Content of current directory (PWD) where checkout should have created 'my_project_code':"
        ls -la .
        echo "------------------------------------"
        echo "Content of 'my_project_code' directory:"
        ls -la ./my_project_code || echo "ls failed for ./my_project_code"

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18' 

    - name: Install pnpm
      run: npm install -g pnpm 

    - name: Install dependencies with pnpm
      shell: bash 
      working-directory: ./my_project_code # Usamos la carpeta que creamos
      run: pnpm install 

    - name: Build the executable
      shell: bash 
      working-directory: ./my_project_code # Usamos la carpeta que creamos
      run: pnpm run build-exe 

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: PetroleumPumpDesigner-Windows 
        path: ./my_project_code/PetroleumPumpDesigner.exe # Ruta relativa a la carpeta que creamos
