name: Build Windows Executable

on:
  push:
    branches: [ main ] 
  workflow_dispatch: 

jobs:
  build:
    runs-on: windows-latest 

    steps:
    # Paso 1: Solo checkout, sin path, para ver dónde realmente pone las cosas
    - name: Checkout code (default behavior)
      uses: actions/checkout@v4

    # Paso 2: Listar TODO desde GITHUB_WORKSPACE para entender la estructura
    - name: Debug Initial Directory Structure
      shell: bash
      run: |
        echo "GITHUB_WORKSPACE: ${{ github.workspace }}"
        echo "Initial PWD: $(pwd)"
        echo "------------------------------------"
        echo "Content of GITHUB_WORKSPACE (RECURSIVE ls -R):"
        ls -R ${{ github.workspace }} || echo "ls -R failed for GITHUB_WORKSPACE"

    # Pasos siguientes comentados hasta que entendamos el checkout
    # - name: Set up Node.js
    #   uses: actions/setup-node@v4
    #   with:
    #     node-version: '18' 

    # - name: Install pnpm
    #   run: npm install -g pnpm 

    # - name: Determine Code Directory and Install Dependencies
    #   shell: bash
    #   run: |
    #     # Intentar encontrar el package.json
    #     CODE_DIR_WITH_PACKAGE_JSON=$(find ${{ github.workspace }} -name 'package.json' -printf '%h' -quit)
    #     if [ -z "$CODE_DIR_WITH_PACKAGE_JSON" ]; then
    #       echo "package.json not found anywhere under ${{ github.workspace }}"
    #       exit 1
    #     fi
    #     echo "Found package.json in: $CODE_DIR_WITH_PACKAGE_JSON"
    #     cd "$CODE_DIR_WITH_PACKAGE_JSON"
    #     echo "Current directory for pnpm install: $(pwd)"
    #     pnpm install

    # - name: Build the executable
    #   shell: bash
    #   # Asumiendo que CODE_DIR_WITH_PACKAGE_JSON fue el correcto
    #   run: |
    #     CODE_DIR_WITH_PACKAGE_JSON=$(find ${{ github.workspace }} -name 'package.json' -printf '%h' -quit)
    #     cd "$CODE_DIR_WITH_PACKAGE_JSON"
    #     pnpm run build-exe 

    # - name: Upload artifact
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: PetroleumPumpDesigner-Windows 
    #     # Asumiendo que CODE_DIR_WITH_PACKAGE_JSON fue el correcto
    #     # y que el .exe se crea ahí
    #     path: $(find ${{ github.workspace }} -name 'package.json' -printf '%h' -quit)/PetroleumPumpDesigner.exe
