name: Build Windows Executable

on:
  push:
    branches: [ main ] 
  workflow_dispatch: 

jobs:
  build:
    runs-on: windows-latest 

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      # Sin 'path'. Esto clonará en ${{ github.workspace }}/<nombre-del-repo>
      # Si github.workspace = D:\a\X\X y repo = X, código estará en D:\a\X\X\X

    - name: Define code directory
      id: paths
      shell: bash
      run: |
        # Construye la ruta donde realmente está el código
        # GITHUB_WORKSPACE ya es D:\a\PetroleumPumpDesigner\PetroleumPumpDesigner
        # El checkout crea OTRA PetroleumPumpDesigner dentro.
        # Usamos el nombre del repositorio para construir la ruta.
        # El nombre del repo se puede obtener de github.repository (ej: 'usuario/nombre-repo')
        # y extraemos solo 'nombre-repo'.
        REPO_NAME=$(basename ${{ github.repository }})
        echo "CODE_DIR=${{ github.workspace }}/$REPO_NAME" >> $GITHUB_OUTPUT

    - name: Debug Directory Structure
      shell: bash
      run: |
        echo "GITHUB_WORKSPACE: ${{ github.workspace }}"
        echo "Code is expected in: ${{ steps.paths.outputs.CODE_DIR }}"
        echo "------------------------------------"
        echo "Content of GITHUB_WORKSPACE:"
        ls -la ${{ github.workspace }}
        echo "------------------------------------"
        echo "Content of CODE_DIR ( ${{ steps.paths.outputs.CODE_DIR }} ):"
        ls -la ${{ steps.paths.outputs.CODE_DIR }} || echo "ls failed for CODE_DIR"

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18' 

    - name: Install pnpm
      run: npm install -g pnpm 

    - name: Install dependencies with pnpm
      working-directory: ${{ steps.paths.outputs.CODE_DIR }}
      run: pnpm install 

    - name: Build the executable
      working-directory: ${{ steps.paths.outputs.CODE_DIR }}
      run: pnpm run build-exe 

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: PetroleumPumpDesigner-Windows 
        path: ${{ steps.paths.outputs.CODE_DIR }}/PetroleumPumpDesigner.exe
