name: Build Windows Executable

on:
  push:
    branches: [ main ] 
  workflow_dispatch: 

jobs:
  build:
    runs-on: windows-latest 

    defaults:
      run:
        # Este es el directorio donde está tu código clonado
        working-directory: ./PetroleumPumpDesigner 

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18' # <-- ¡VERIFICA Y AJUSTA ESTA VERSIÓN!

    - name: Install pnpm
      # Ejecuta este comando en el directorio de trabajo raíz del runner, no en la subcarpeta del proyecto
      working-directory: ${{ github.workspace }} # <--- ¡CAMBIO IMPORTANTE AQUÍ!
      run: npm install -g pnpm 

    - name: Install dependencies with pnpm
      # Este usará el working-directory de 'defaults'
      run: pnpm install 

    - name: Build the executable
      # Este usará el working-directory de 'defaults'
      run: pnpm run build-exe 

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: PetroleumPumpDesigner-Windows 
        # El path del artefacto es relativo al working-directory de 'defaults'
        path: PetroleumPumpDesigner.exe 
